dist: trusty
sudo: required
osx_image: xcode8.3
language: java

os:
  - linux

env:
  - V=0.16.0 OS=linux

before_install:
  - |
    sysctl kernel.unprivileged_userns_clone=1
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
  - |
    bazel \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --local_resources=400,1,1.0 \
      //...
