dist: trusty
sudo: required
osx_image: xcode8.3
language: java

os:
- linux

env:
- V=0.16.0 OS=linux

cache:
  directories:
  - $HOME/.cache/bazel

before_install:
- |
  sudo mkdir -p $HOME/.cache/bazel
  sudo chown -R travis:travis $HOME/.cache/bazel
  sudo chmod -R 777 $HOME/.cache/bazel
  sudo rm -rf $HOME/.cache/bazel/_bazel_travis/install
  sysctl kernel.unprivileged_userns_clone=1
  URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
  wget -O install.sh "${URL}"
  chmod +x install.sh
  ./install.sh --user
  rm -f install.sh

script:
- |
  bazel \
    --output_base=$HOME/.cache/bazel \
    --host_jvm_args=-Xmx500m \
    --host_jvm_args=-Xms500m \
    test \
    --experimental_repository_cache="$HOME/.bazel_repository_cache" \
    --local_resources=400,1,1.0 \
    //...
